### ISSUE TITLE
[Question] Using a VPC Lookup in another AWS Account (same organisation) for RDS Construct

### ISSUE THREAD

**Issue by brifiction** [bobbyhadz/aws-cdk-rds-example#1]
Hello Bobby,

Great article by the way, thank you for writing as you've helped my self-learning journey with `aws-cdk`.

I have a question about using a VPC Lookup and RDS Construct, but it's for attaching a VPC that belongs to another AWS Account (in same Organisational Unit).

Based on your RDS article as a starting example, do I need to write some pre-requisite code blocks that requires 'assuming a Role' to successfully fetch the VPC from that AWS Account? Basically, is there a 'elegant way' to fetch the VPC ID or ARN programmatically with `aws-cdk`, cross-accounts and cross-stacks?

Note, my project is on `serverless-stack`, as it does not have a `cdk.json` file, but it still have a `cdk.context.json` file - the IAM ID it contains belongs to AWS Account A.

Example:
```
Infrastructure OU
- accountA@company.com
  - VPCStack
- accountB@company.com
  - RDSStack
```

Any advice will be much appreciated, truly stuck with this use-case 😓

**Comment by bobbyhadz** [comment]
Hi Brian, 
I haven't used CDK or AWS for work in a while, so I'm very out of the loop.
Haven't had to do something similar, so I don't know. Sorry.

**Comment by brifiction** [comment]
Hey Bobby,

No worries, thanks for getting back to my question so fast - much appreciated. I'll close this question and keep looking.
